---

rocketchat_service: 'https://{{ stage }}-chat-rehabilitation.wehost.asia'

superset_dashboard_id_for_global_admin:   'ebb93bc0-bde5-4f76-b991-c1954e0813a9'
superset_dashboard_id_for_country_admin:  '48bc1e88-80ae-4fa4-9b5b-2ff937c5ad2f'
superset_dashboard_id_for_clinic_admin:   '8044e76d-252d-46c0-b7b1-4ca5f88a5e70'
superset_dashboard_id_for_therapist:      '71e3cc54-1150-4984-86be-d6782e06e84f'